// <auto-generated />
using System;
using HotelTools.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.EntityFrameworkCore.SqlServer.Metadata.Internal;

#nullable disable

namespace HotelTools.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class AddFK_Huespedes_HabitacionesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelTools.Models.Huesped", b =>
                {
                    b.Property<decimal>("ID_Huesped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Huesped"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DiasAlojados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaOut")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_Idioma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_NroHab")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("ID_Pais")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID_Huesped");

                    b.HasIndex("ID_NroHab");

                    b.ToTable("Huespedes", "Quejas");

                    b.HasOne("HotelTools.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("ID_NroHab")
                        .HasConstraintName("FK_Huespedes_Habitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
