// <auto-generated />
using System;
using HotelTools.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelTools.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20260820140016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelTools.Models.Cargo", b =>
                {
                    b.Property<decimal>("ID_Cargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Cargo"));

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Cargo");

                    b.ToTable("Cargo", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.CategoriaHabitacion", b =>
                {
                    b.Property<decimal>("ID_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Categoria"));

                    b.Property<string>("TipoHab")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Categoria");

                    b.ToTable("Categorias", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.CategoriaProducto", b =>
                {
                    b.Property<decimal>("ID_CategoriasPro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_CategoriasPro"));

                    b.Property<string>("NombreCatProductos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID_CategoriasPro");

                    b.ToTable("CategoriasProductos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Departamento", b =>
                {
                    b.Property<decimal>("ID_Departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Departamento"));

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID_Departamento");

                    b.ToTable("Departamentos", "General");
                });

            modelBuilder.Entity("HotelTools.Models.Empleado", b =>
                {
                    b.Property<decimal>("ID_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Empleado"));

                    b.Property<byte>("Activo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_Cargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Departamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Rol")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Empleado");

                    b.ToTable("Empleados", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.Habitacion", b =>
                {
                    b.Property<decimal>("ID_NroHab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_NroHab"));

                    b.Property<string>("DescripcionHab")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("ID_CategoriasFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxPersonas")
                        .HasColumnType("int");

                    b.HasKey("ID_NroHab");

                    b.ToTable("Habitaciones", "General");
                });

            modelBuilder.Entity("HotelTools.Models.HabitacionProductos", b =>
                {
                    b.Property<decimal>("ID_HabProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_HabProductos"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("ID_HabFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_ProductosFK")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_HabProductos");

                    b.ToTable("HabitacionProductos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Modelo", b =>
                {
                    b.Property<decimal>("ID_Modelos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Modelos"));

                    b.Property<string>("NombreModelos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Modelos");

                    b.ToTable("Modelos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.PaqueteProducto", b =>
                {
                    b.Property<decimal>("ID_Paquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Paquete"));

                    b.Property<decimal>("ID_CategoriaHabitacionFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID_Paquete");

                    b.ToTable("PaqueteProducto", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.PaqueteProductoDetalle", b =>
                {
                    b.Property<decimal>("ID_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("ID_PaqueteFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_TipoProductoFK")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Detalle");

                    b.HasIndex("ID_PaqueteFK");

                    b.HasIndex("ID_TipoProductoFK");

                    b.ToTable("PaqueteProductoDetalle", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Permiso", b =>
                {
                    b.Property<decimal>("ID_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Permiso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID_Permiso");

                    b.ToTable("Permisos", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.Producto", b =>
                {
                    b.Property<decimal>("ID_Productos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Productos"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Nuevo");

                    b.Property<DateTime?>("FechaReparacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_CategoriaProFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_HabitacionFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_ModelosFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_NroFacturaFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("ReparadoPor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Productos");

                    b.ToTable("Productos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Proveedor", b =>
                {
                    b.Property<decimal>("ID_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Proveedor"));

                    b.Property<decimal>("ID_RazonSocialFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_RepresentanteFK")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Proveedor");

                    b.ToTable("Proveedores", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.RazonSocial", b =>
                {
                    b.Property<decimal>("ID_RazonSocial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_RazonSocial"));

                    b.Property<decimal>("Cuil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DireccionDigital")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DireccionFisica")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TelefonoFijo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_RazonSocial");

                    b.ToTable("RazonSocial", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Representante", b =>
                {
                    b.Property<decimal>("ID_Representante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Representante"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_Representante");

                    b.ToTable("Representante", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Rol", b =>
                {
                    b.Property<decimal>("ID_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Rol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Rol");

                    b.ToTable("Rol", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.RolPermiso", b =>
                {
                    b.Property<decimal>("ID_RolPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_RolPermiso"));

                    b.Property<decimal?>("ID_Departamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Permiso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Rol")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_RolPermiso");

                    b.ToTable("RolPermisos", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.SesionActiva", b =>
                {
                    b.Property<decimal>("ID_SesionesActiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_SesionesActiva"));

                    b.Property<bool>("EstadoSesion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_Empleado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_SesionesActiva");

                    b.ToTable("SesionesActivas", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.TipoProducto", b =>
                {
                    b.Property<decimal>("ID_TipoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_TipoProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ID_CategoriaProFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_ModelosFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID_TipoProducto");

                    b.ToTable("TipoProducto", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.PaqueteProductoDetalle", b =>
                {
                    b.HasOne("HotelTools.Models.PaqueteProducto", "Paquete")
                        .WithMany()
                        .HasForeignKey("ID_PaqueteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelTools.Models.TipoProducto", "TipoProducto")
                        .WithMany()
                        .HasForeignKey("ID_TipoProductoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");

                    b.Navigation("TipoProducto");
                });
#pragma warning restore 612, 618
        }
    }
}
