// <auto-generated />
using System;
using HotelTools.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelTools.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelTools.Models.Cargo", b =>
                {
                    b.Property<decimal>("ID_Cargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Cargo"));

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Cargo");

                    b.ToTable("Cargo", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.CategoriaHabitacion", b =>
                {
                    b.Property<decimal>("ID_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Categoria"));

                    b.Property<string>("TipoHab")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Categoria");

                    b.ToTable("Categorias", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.CategoriaProducto", b =>
                {
                    b.Property<decimal>("ID_CategoriasPro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_CategoriasPro"));

                    b.Property<string>("NombreCatProductos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID_CategoriasPro");

                    b.ToTable("CategoriasProductos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.CategoriaQueja", b =>
                {
                    b.Property<decimal>("ID_CategoriaQueja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_CategoriaQueja"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID_CategoriaQueja");

                    b.ToTable("CategoriasQueja", "Quejas");
                });

            modelBuilder.Entity("HotelTools.Models.Departamento", b =>
                {
                    b.Property<decimal>("ID_Departamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Departamento"));

                    b.Property<string>("NombreDepartamento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID_Departamento");

                    b.ToTable("Departamentos", "General");
                });

            modelBuilder.Entity("HotelTools.Models.Empleado", b =>
                {
                    b.Property<decimal>("ID_Empleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Empleado"));

                    b.Property<byte>("Activo")
                        .HasColumnType("tinyint");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_Cargo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Departamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Rol")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroContacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Empleado");

                    b.ToTable("Empleados", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.EstadoQueja", b =>
                {
                    b.Property<decimal>("ID_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Estado"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Estado");

                    b.ToTable("Estados", "Quejas");
                });

            modelBuilder.Entity("HotelTools.Models.Habitacion", b =>
                {
                    b.Property<decimal>("ID_NroHab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_NroHab"));

                    b.Property<string>("DescripcionHab")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("ID_CategoriasFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxPersonas")
                        .HasColumnType("int");

                    b.HasKey("ID_NroHab");

                    b.ToTable("Habitaciones", "General");
                });

            modelBuilder.Entity("HotelTools.Models.HabitacionProductos", b =>
                {
                    b.Property<decimal>("ID_HabProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_HabProductos"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("EsNativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("EsPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRetiro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_HabFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_ProductosFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PrestadoFuera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ID_HabProductos");

                    b.ToTable("HabitacionProductos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.HistorialQueja", b =>
                {
                    b.Property<decimal>("ID_Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Orden"));

                    b.Property<bool>("Aprobado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("ID_Compra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Empleado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Estado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Imagen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Quejas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("observaciones")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID_Orden");

                    b.ToTable("Historial", "Quejas");
                });

            modelBuilder.Entity("HotelTools.Models.Huesped", b =>
                {
                    b.Property<decimal>("ID_Huesped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Huesped"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DiasAlojados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaOut")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_Idioma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_NroHab")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("ID_Pais")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID_Huesped");

                    b.HasIndex("ID_NroHab");

                    b.ToTable("Huespedes", "Quejas");
                });

            modelBuilder.Entity("HotelTools.Models.Idioma", b =>
                {
                    b.Property<decimal>("ID_Idioma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Idioma"));

                    b.Property<string>("NombreIdioma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Idioma");

                    b.ToTable("Idioma", "General");
                });

            modelBuilder.Entity("HotelTools.Models.ImagenQueja", b =>
                {
                    b.Property<decimal>("idImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("idImagen"));

                    b.Property<byte[]>("imagen")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("idImagen");

                    b.ToTable("Imagen", "Quejas");
                });

            modelBuilder.Entity("HotelTools.Models.Modelo", b =>
                {
                    b.Property<decimal>("ID_Modelos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Modelos"));

                    b.Property<string>("NombreModelos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Modelos");

                    b.ToTable("Modelos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Pais", b =>
                {
                    b.Property<decimal>("ID_PaisOrigen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_PaisOrigen"));

                    b.Property<string>("NombrePais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PaisOrigen");

                    b.ToTable("Pais", "General");
                });

            modelBuilder.Entity("HotelTools.Models.PaqueteProducto", b =>
                {
                    b.Property<decimal>("ID_Paquete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Paquete"));

                    b.Property<decimal>("ID_CategoriaHabitacionFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID_Paquete");

                    b.ToTable("PaqueteProducto", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.PaqueteProductoDetalle", b =>
                {
                    b.Property<decimal>("ID_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("ID_PaqueteFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_TipoProductoFK")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Detalle");

                    b.HasIndex("ID_PaqueteFK");

                    b.HasIndex("ID_TipoProductoFK");

                    b.ToTable("PaqueteProductoDetalle", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Permiso", b =>
                {
                    b.Property<decimal>("ID_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Permiso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID_Permiso");

                    b.ToTable("Permisos", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.PrioridadQueja", b =>
                {
                    b.Property<decimal>("ID_Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Prioridad"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NombrePrioridad")
                        .HasColumnType("int");

                    b.HasKey("ID_Prioridad");

                    b.ToTable("Prioridad", "Quejas");
                });

            modelBuilder.Entity("HotelTools.Models.Producto", b =>
                {
                    b.Property<decimal>("ID_Productos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Productos"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Nuevo");

                    b.Property<DateTime?>("FechaReparacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_CategoriaProFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_HabitacionFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_HabitacionOrigenFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_ModelosFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_NroFacturaFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Prestado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Prestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("ReparadoPor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Productos");

                    b.ToTable("Productos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.ProductosMovimientos", b =>
                {
                    b.Property<decimal>("ID_ProductosMovimientos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_ProductosMovimientos"));

                    b.Property<DateTime>("FechaMov")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_Empleado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_EmpleadoMov")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_HabDestino")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_HabOrigen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_HabitacionCasa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Productos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMovimiento")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_ProductosMovimientos");

                    b.ToTable("ProductosMovimientos", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Proveedor", b =>
                {
                    b.Property<decimal>("ID_Proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Proveedor"));

                    b.Property<decimal>("ID_RazonSocialFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_RepresentanteFK")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Proveedor");

                    b.ToTable("Proveedores", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Queja", b =>
                {
                    b.Property<decimal>("ID_Quejas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Quejas"));

                    b.Property<decimal>("ID_DepartamentoEjecuta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_DepartamentoRecibe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Empleado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_EmpleadoAsignacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ID_Estado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Habitaciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Huesped")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Prioridad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quejas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Quejas");

                    b.ToTable("Quejas", "Quejas");
                });

            modelBuilder.Entity("HotelTools.Models.QuejaImagen", b =>
                {
                    b.Property<decimal>("ID_QuejaImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_QuejaImagen"));

                    b.Property<DateTime>("FechaAdjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("ID_Imagen")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Queja")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_QuejaImagen");

                    b.ToTable("QuejaImagen", "Quejas");
                });

            modelBuilder.Entity("HotelTools.Models.RazonSocial", b =>
                {
                    b.Property<decimal>("ID_RazonSocial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_RazonSocial"));

                    b.Property<decimal>("Cuil")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DireccionDigital")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DireccionFisica")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TelefonoFijo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_RazonSocial");

                    b.ToTable("RazonSocial", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Representante", b =>
                {
                    b.Property<decimal>("ID_Representante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Representante"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonoCelular")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID_Representante");

                    b.ToTable("Representante", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Rol", b =>
                {
                    b.Property<decimal>("ID_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_Rol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Rol");

                    b.ToTable("Rol", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.RolPermiso", b =>
                {
                    b.Property<decimal>("ID_RolPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_RolPermiso"));

                    b.Property<decimal?>("ID_Departamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Permiso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_Rol")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_RolPermiso");

                    b.ToTable("RolPermisos", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.SesionActiva", b =>
                {
                    b.Property<decimal>("ID_SesionesActiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_SesionesActiva"));

                    b.Property<bool>("EstadoSesion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ID_Empleado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_SesionesActiva");

                    b.ToTable("SesionesActivas", "Empleados");
                });

            modelBuilder.Entity("HotelTools.Models.TipoProducto", b =>
                {
                    b.Property<decimal>("ID_TipoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("ID_TipoProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ID_CategoriaProFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ID_ModelosFK")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID_TipoProducto");

                    b.ToTable("TipoProducto", "Inventarios");
                });

            modelBuilder.Entity("HotelTools.Models.Huesped", b =>
                {
                    b.HasOne("HotelTools.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("ID_NroHab")
                        .HasConstraintName("FK_Huespedes_Habitaciones");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("HotelTools.Models.PaqueteProductoDetalle", b =>
                {
                    b.HasOne("HotelTools.Models.PaqueteProducto", "Paquete")
                        .WithMany()
                        .HasForeignKey("ID_PaqueteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelTools.Models.TipoProducto", "TipoProducto")
                        .WithMany()
                        .HasForeignKey("ID_TipoProductoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");

                    b.Navigation("TipoProducto");
                });
#pragma warning restore 612, 618
        }
    }
}
